providers = ['php', 'node']

[phases.setup]
nixPkgs = [
  'php82',
  'php82Extensions.gd',
  'php82Extensions.pdo_mysql',
  'php82Extensions.mbstring',
  'php82Extensions.tokenizer',
  'php82Extensions.xml',
  'php82Extensions.bcmath',
  'php82Extensions.zip',
  'php82Extensions.curl',
  'php82Extensions.fileinfo',
  'php82Packages.composer',
  'nodejs_20'
]

[variables]
NIXPACKS_PHP_ROOT_DIR = '/app/public'
